/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.test.helloandroid;

public final class R {
    public static final class attr {
    }
    public static final class layout {
        public static final int activity_main=0x7f020000;
        public static final int activity_test=0x7f020001;
    }
    public static final class raw {
        public static final int classes=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int hello_msg=0x7f040001;
        public static final int menu_settings=0x7f040002;
        public static final int title_activity_main=0x7f040003;
    }
}
